### PR TITLE
Add test for the latest failure

### PR DESCRIPTION
**Pull request by jakub-id**

### CODE REVIEW

**Review by adamdickmeiss — COMMENTED** [review]
Is it worth adding this if it's valid?

I understand why you tried the test to see if xmlfixer broke it

**Comment by jakub-id** [comment]
No, we're not adding this. It's a draft to illustrate that this response is fine. I assume that we somehow got the wrong response back. Maybe David used wrong resumption token?

**Comment by adamdickmeiss** [comment]
> No, we're not adding this. It's a draft to illustrate that this response is fine. I assume that we somehow got the wrong response back. Maybe David used wrong resumption token?

Most likely.

**Review by adamdickmeiss — APPROVED** [review]
FWIW, I'm ok with merging this now.

**Comment by jakub-id** [comment]
@adamdickmeiss Ok to close without merging?

**Comment by adamdickmeiss** [comment]
> @adamdickmeiss Ok to close without merging?

Yes.

**Pull request closed without merging**
